### ISSUE TITLE
Not show Multiple Person Profile

### ISSUE THREAD

**Issue by devangbhuva97** [piotrl/github-profile-card#17]
I want to try display multiple person profile but only one person profile displayed. 
Reason: Data only come in first profile.  There is no data in second profile.

![code-1](https://user-images.githubusercontent.com/20520415/27506786-5435b0b4-58de-11e7-99b0-e14928599be6.PNG)
![code-2](https://user-images.githubusercontent.com/20520415/27506787-5462d134-58de-11e7-8a9a-6d49f6d8ee7d.PNG)
![output-1](https://user-images.githubusercontent.com/20520415/27506788-547a089a-58de-11e7-82d1-aa7d11e3f0a6.PNG)
![output-2](https://user-images.githubusercontent.com/20520415/27506789-549e35a8-58de-11e7-8f70-990271d5f97e.PNG)

**Comment by piotrl** [comment]
I'm glad you took the time to report that @devangbhuva97. Thanks!

It's a bug, I do cache requests to avoid GitHub API limitations and I naively assumed that only one profile will be displayed.

I'm gonna fix it and release version 2.0.2.

**Comment by devangbhuva97** [comment]
thank and all the best for fix bug

**Comment by piotrl** [comment]
@devangbhuva97 I was wrong. It's not a bug actually ;)

Only one widget is rendered because in HTML `id="github-profile"` is used twice.
On one page, `id` attribute has to be unique (according to HTML specification).
Every next element with the same `id` is ignored.

### Solution for you

**HTML** (only changed IDs)
```
<div id="github-card-1"
         data-max-repos="1"
         data-username="JimishF">
</div>
<div id="github-card-2"
         data-max-repos="1"
         data-username="devangbhuva97">
</div>
```

**JavaScript** (you have to initialize widgets with custom template)
```
new GitHubCard({
    template: '#github-card-1'
}).init();

new GitHubCard({
    template: '#github-card-2'
}).init();
```

**Comment by devangbhuva97** [comment]
Thank you so much for giving solution.
